syntax = "proto3";

package stock_list;

service StockList {
  rpc GetStockListFromInvezgo(GetStockListFromInvezgoRequest) returns (GetStockListFromInvezgoResponse);
  rpc GetStockListFromScylla(GetStockListFromScyllaRequest) returns (GetStockListFromScyllaResponse);
}

message GetStockListFromInvezgoRequest {}

message GetStockListFromInvezgoResponse {
  bool success = 1;
  string message = 2;
}

message GetStockListFromScyllaRequest {}

message StockListRow {
  string code = 1;
  string name = 2;
  string sector = 3;
  string logo = 4;
}

message GetStockListFromScyllaResponse {
  repeated StockListRow items = 1;
}
