[package]
name = "portofolio"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
futures-util = "0.3"
prost = { version = "0.13", features = ["std", "derive"] }
scylla = { version = "1.5", features = ["chrono-04"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
tonic = { version = "0.12", features = ["transport"] }
user = { path = "../user" }
worker_scrapping = { path = "../../worker_scrapping" }

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3"
tonic-build = "0.12"
