[package]
name = "create_database"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "create_bandarmology"
path = "src/bin/create_bandarmology.rs"

[[bin]]
name = "create_emiten_trending"
path = "src/bin/create_emiten_trending.rs"

[[bin]]
name = "create_portofolio"
path = "src/bin/create_portofolio.rs"

[[bin]]
name = "create_emiten_list"
path = "src/bin/create_emiten_list.rs"

[[bin]]
name = "create_user"
path = "src/bin/create_user.rs"

[[bin]]
name = "create_broker_name"
path = "src/bin/create_broker_name.rs"

[[bin]]
name = "create_rule"
path = "src/bin/create_rule.rs"

[[bin]]
name = "create_catatan"
path = "src/bin/create_catatan.rs"

[dependencies]
bcrypt = "0.16"
dotenvy = "0.15"
scylla = "1.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "fs"] }
uuid = { version = "1", features = ["v4"] }
