[workspace]
members = [
    "app",
    "crate/stock_list",
    "crate/user",
    "crate/top_gainer_loser",
    "crate/bandarmology",
    "crate/broker",
    "crate/portofolio",
    "crate/portofolio_equity",
    "crate/portofolio_history",
    "crate/pending_order",
    "crate/emiten_trending",
    "crate/chart",
    "crate/haka_haki",
    "crate/msci",
    "crate/market_holiday",
    "crate/hari_libur",
    "crate/stockbit_browser",
    "crate/wyckoff_glosary",
    "crate/tls",
    "crate/grpc_stream",
    "crate/grpc_server",
    "worker_scrapping",
]
resolver = "2"

[patch.crates-io]
tonic = { path = "third_party/tonic" }
