[workspace]
members = [
    "app",
    "crate/bandarmology",
    "crate/broker",
    "crate/create_database",
    "crate/emiten_list",
    "crate/emiten_trending",
    "crate/emiten_trending_count",
    "crate/gcs",
    "crate/pending_order",
    "crate/portofolio",
    "crate/portofolio_equity",
    "crate/stockbit_browser",
    "crate/tls",
    "crate/user",
    "worker_scrapping",
]
resolver = "2"
