[workspace]
members = [
    "app",
    "crate/stock_list",
    "crate/user",
    "crate/top_gainer_loser",
    "crate/bandarmology",
    "crate/broker",
    "crate/portofolio",
    "crate/portofolio_equity",
    "crate/pending_order",
    "crate/emiten_trending",
    "crate/stockbit_browser",
    "crate/tls",
    "worker_scrapping",
]
resolver = "2"
