[package]
name = "invezgood"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "invezgood"
path = "src/main.rs"

[dependencies]
dotenvy = "0.15"
stock_list = { path = "../crate/stock_list" }
user = { path = "../crate/user" }
top_gainer_loser = { path = "../crate/top_gainer_loser" }
bandarmology = { path = "../crate/bandarmology" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tls = { path = "../crate/tls" }
tonic = { version = "0.12", features = ["tls", "gzip"] }
tonic-reflection = "0.12"
prost = "0.13"

[build-dependencies]
tonic-build = "0.12"
