[package]
name = "haka_haki"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
moka = { version = "0.12", features = ["future"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
scylla = { version = "1.5", features = ["chrono-04"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tonic = "0.12"
prost = "0.13"
redis = { version = "0.27", default-features = false, features = ["tokio-comp", "connection-manager"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
user = { path = "../user" }

[build-dependencies]
tonic-build = "0.12"
