[package]
name = "worker_scrapping"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "worker_scrapping"
path = "stockbit_scrapper_worker.rs"

[dependencies]
stockbit_browser = { path = "../crate/stockbit_browser" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
chromiumoxide = "0.9"
dotenvy = "0.15"
scylla = { version = "1.5", features = ["chrono-04"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "fs", "signal"] }
uuid = { version = "1", features = ["v4"] }
