[package]
name = "wyckoff_glossary"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
futures-util = "0.3"
prost = { version = "0.13", features = ["std", "derive"] }
scylla = "1.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
tonic = { version = "0.12", features = ["transport"] }
user = { path = "../user" }

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3"
tonic-build = "0.12"
